sudo: false

language: go

before_script:
  - go get -u github.com/golang/lint/golint

script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - test -z "$(golint ./...     | tee /dev/stderr)"
  - go vet ./...
  - go test ./...
